"""
export.py -- Export results to PDF and Word (.docx)
Handles Financial Extraction and Summarization outputs.
"""

from __future__ import annotations
import io
from datetime import datetime


def _timestamp() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


# ── Word (.docx) ──────────────────────────────────────────────────────

def financial_to_docx(report) -> bytes:
    """Export a FinancialReport to a styled .docx, returned as bytes."""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise ImportError("Run: pip install python-docx")

    doc = Document()

    # Title
    title = doc.add_heading("Financial Extraction Report", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph(f"Generated by AutoChain · {_timestamp()}").alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph()

    # Summary table
    doc.add_heading("Key Figures", level=1)
    table = doc.add_table(rows=1, cols=2)
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    hdr[0].text = "Field"
    hdr[1].text = "Value"
    for label, value in [
        ("Company",    report.company),
        ("Revenue",    report.revenue),
        ("Net Income", report.net_income),
        ("EBITDA",     report.ebitda),
    ]:
        if value:
            row = table.add_row().cells
            row[0].text = label
            row[1].text = value

    doc.add_paragraph()

    # Key Metrics
    if report.key_metrics:
        doc.add_heading("Key Metrics", level=1)
        for m in report.key_metrics:
            doc.add_paragraph(m, style="List Bullet")
        doc.add_paragraph()

    # Risk Factors
    if report.risks:
        doc.add_heading("Risk Factors", level=1)
        for r in report.risks:
            doc.add_paragraph(r, style="List Bullet")
        doc.add_paragraph()

    # Outlook
    if report.outlook:
        doc.add_heading("Outlook", level=1)
        doc.add_paragraph(report.outlook)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def summary_to_docx(result, source_filename: str = "") -> bytes:
    """Export a SummaryOutput to a styled .docx, returned as bytes."""
    try:
        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise ImportError("Run: pip install python-docx")

    doc = Document()

    title = doc.add_heading("Document Summary", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle = f"Generated by AutoChain · {_timestamp()}"
    if source_filename:
        subtitle += f" · Source: {source_filename}"
    doc.add_paragraph(subtitle).alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph()

    doc.add_heading("Summary", level=1)
    doc.add_paragraph(result.raw_summary)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ── PDF ───────────────────────────────────────────────────────────────

def financial_to_pdf(report) -> bytes:
    """Export a FinancialReport to a clean PDF, returned as bytes."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    except ImportError:
        raise ImportError("Run: pip install reportlab")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # Header
    story.append(Paragraph("Financial Extraction Report", styles["Title"]))
    story.append(Paragraph(f"Generated by AutoChain · {_timestamp()}", styles["Normal"]))
    story.append(Spacer(1, 0.5*cm))

    # Key figures table
    story.append(Paragraph("Key Figures", styles["Heading1"]))
    rows = [["Field", "Value"]]
    for label, value in [
        ("Company",    report.company),
        ("Revenue",    report.revenue),
        ("Net Income", report.net_income),
        ("EBITDA",     report.ebitda),
        ("Outlook",    report.outlook),
    ]:
        if value:
            rows.append([label, value])

    if len(rows) > 1:
        t = Table(rows, colWidths=[4*cm, 12*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), colors.HexColor("#1f6feb")),
            ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
            ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f6f8fa"), colors.white]),
            ("GRID",        (0, 0), (-1, -1), 0.5, colors.HexColor("#30363d")),
            ("PADDING",     (0, 0), (-1, -1), 6),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.4*cm))

    # Key Metrics
    if report.key_metrics:
        story.append(Paragraph("Key Metrics", styles["Heading1"]))
        for m in report.key_metrics:
            story.append(Paragraph(f"• {m}", styles["Normal"]))
        story.append(Spacer(1, 0.4*cm))

    # Risks
    if report.risks:
        story.append(Paragraph("Risk Factors", styles["Heading1"]))
        for r in report.risks:
            story.append(Paragraph(f"• {r}", styles["Normal"]))
        story.append(Spacer(1, 0.4*cm))

    doc.build(story)
    return buf.getvalue()


def summary_to_pdf(result, source_filename: str = "") -> bytes:
    """Export a SummaryOutput to a clean PDF, returned as bytes."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import cm
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    except ImportError:
        raise ImportError("Run: pip install reportlab")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Document Summary", styles["Title"]))
    subtitle = f"Generated by AutoChain · {_timestamp()}"
    if source_filename:
        subtitle += f" · Source: {source_filename}"
    story.append(Paragraph(subtitle, styles["Normal"]))
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph("Summary", styles["Heading1"]))

    # Split on newlines and add each paragraph
    for line in result.raw_summary.split("\n"):
        line = line.strip()
        if line:
            story.append(Paragraph(line, styles["Normal"]))
            story.append(Spacer(1, 0.2*cm))

    doc.build(story)
    return buf.getvalue()